// Code generated by MockGen. DO NOT EDIT.
// Source: calculator.go

// Package calculator is a generated GoMock package.
package calculator

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockDB is a mock of DB interface.
type MockDB struct {
	ctrl     *gomock.Controller
	recorder *MockDBMockRecorder
}

// MockDBMockRecorder is the mock recorder for MockDB.
type MockDBMockRecorder struct {
	mock *MockDB
}

// NewMockDB creates a new mock instance.
func NewMockDB(ctrl *gomock.Controller) *MockDB {
	mock := &MockDB{ctrl: ctrl}
	mock.recorder = &MockDBMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDB) EXPECT() *MockDBMockRecorder {
	return m.recorder
}

// CreateCalc mocks base method.
func (m *MockDB) CreateCalc(ctx context.Context, lhs, rhs int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCalc", ctx, lhs, rhs)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateCalc indicates an expected call of CreateCalc.
func (mr *MockDBMockRecorder) CreateCalc(ctx, lhs, rhs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCalc", reflect.TypeOf((*MockDB)(nil).CreateCalc), ctx, lhs, rhs)
}
